name       : opencv
version    : 4.5.2
release    : 27
source     :
    - https://github.com/opencv/opencv/archive/refs/tags/4.5.2.tar.gz : ae258ed50aa039279c3d36afdea5c6ecf762515836b27871a8957c610d0424f8
    - https://github.com/opencv/opencv_contrib/archive/4.5.2/opencv_contrib-4.5.2.tar.gz : 9f52fd3114ac464cb4c9a2a6a485c729a223afb57b9c24848484e55cef0b5c2a
    - https://raw.githubusercontent.com/opencv/opencv_3rdparty/ippicv/master_20191018/ippicv/ippicv_2020_lnx_intel64_20191018_general.tgz : 08627fa5660d52d59309a572dd7db5b9c8aea234cfa5aee0942a1dd903554246
    - https://github.com/opencv/ade/archive/v0.1.1f.zip : 956e2e51da455ebb3d3ed1269dda44d233a2de620e5bdbdb32e0c0bb84b2c912
license    :
    - BSD-3-Clause
    - EULA # ippicv
component  : programming.library
summary    : OpenCV is an open source computer vision and machine learning software library
description: |
    OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - pkgconfig(eigen3)
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(hdf5)
    - pkgconfig(ice)
    - pkgconfig(libavcodec)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libgphoto2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(libwebp)
    - pkgconfig(openblas)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(sm)
    - pkgconfig(xmu)
    - intel-tbb-devel
    - numpy
    - unzip
    - vulkan-headers
rundeps    :
    - numpy
    - devel :
        - qt5-base-devel
setup      : |
    # Use ippicv from $sources
    IPPNAME=$(basename $sources/ippicv_*_lnx_*.tgz)
    IPPMD5SUM=$(md5sum $sources/$IPPNAME | cut -d " " -f1)
    mkdir -p .cache/ippicv
    cp $sources/$IPPNAME .cache/ippicv/$IPPMD5SUM-$IPPNAME
    ADENAME=$(basename $sources/v0.1.1f.zip)
    ADEMD5SUM=$(md5sum $sources/$ADENAME | cut -d " " -f1)
    mkdir -p .cache/ade
    cp $sources/$ADENAME .cache/ade/$ADEMD5SUM-$ADENAME
    tar xf $sources/opencv_contrib-*.tar.gz
    mv opencv_contrib* contrib

    %cmake_ninja \
        -DOPENCV_GENERATE_PKGCONFIG=ON \
        -DOPENCV_EXTRA_MODULES_PATH=$workdir/contrib/modules \
        -DWITH_GPHOTO2=ON \
        -DWITH_IPP=ON \
        -DWITH_OPENGL=ON \
        -DOpenGL_GL_PREFERENCE="GLVND" \
        -DWITH_VULKAN=ON \
        -DWITH_OPENCL=ON \
        -DWITH_TBB=ON \
        -DENABLE_CXX11=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_PERF_TESTS=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_DOCS=OFF \
        -DBUILD_WITH_DEBUG_INFO=OFF \
        -DBUILD_opencv_python2=OFF \
        -DBUILD_opencv_xfeatures2d=OFF \
        -DENABLE_SOLUTION_FOLDERS=ON \
        -DOPENCV_ENABLE_NONFREE=ON \
        -DWITH_QT=ON \
        -DOPENCV_FORCE_PYTHON_LIBS=ON \
        -DENABLE_PRECOMPILED_HEADERS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
