name       : opencv
version    : 3.4.8
release    : 22
source     :
    - https://github.com/opencv/opencv/archive/3.4.7.tar.gz : ea743896a604a6ba1e1c1651ad42c97d0f90165debe9940811c7e0bdaa307526
    - https://raw.githubusercontent.com/opencv/opencv_3rdparty/ippicv/master_20180723/ippicv/ippicv_2019_lnx_intel64_general_20180723.tgz : fc167cb60deb8924339a7050f3da168bb02e221b2d6b8c00139d1fa7eace0c7d
license    :
    - BSD-3-Clause
    - EULA # ippicv
component  : programming
summary    : OpenCV is an open source computer vision and machine learning software
    library
description: |
    OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(ice)
    - pkgconfig(jasper)
    - pkgconfig(libavcodec)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(OpenEXR)
    - pkgconfig(python3)
    - pkgconfig(sm)
    - pkgconfig(xmu)
    - intel-tbb-devel
    - numpy
setup      : |
    #Use ippicv from $sources
    IPPNAME=$(basename $sources/ippicv_*_lnx_*.tgz)
    MD5SUM=$(md5sum $sources/$IPPNAME | cut -d" " -f1)
    mkdir -p .cache/ippicv
    cp $sources/$IPPNAME .cache/ippicv/$MD5SUM-$IPPNAME

    mkdir build && cd build
    %cmake -DWITH_GPHOTO2=OFF \
        -DWITH_IPP=ON \
        -DWITH_OPENGL=ON \
        -DWITH_OPENCL=ON \
        -DWITH_TBB=ON \
        -DENABLE_CXX11=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_PERF_TESTS=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_DOCS=OFF \
        -DBUILD_WITH_DEBUG_INFO=OFF \
        -DENABLE_SOLUTION_FOLDERS=ON \
        -DOPENCV_ENABLE_NONFREE=ON \
        -DWITH_QT=OFF \
        -DOPENCV_FORCE_PYTHON_LIBS=ON \
        -DENABLE_PRECOMPILED_HEADERS=OFF \
           ..
build      : |
    %make -C build
install    : |
    %make_install -C build
