name       : opencv
version    : 3.4.0
release    : 13
source     :
    - https://github.com/opencv/opencv/archive/3.4.0.tar.gz : 678cc3d2d1b3464b512b084a8cca1fad7de207c7abdf2caa1fed636c13e916da
    - https://raw.githubusercontent.com/opencv/opencv_3rdparty/ippicv/master_20170822/ippicv/ippicv_2017u3_lnx_intel64_general_20170822.tgz : 9a4b14a24d31768c3ead0720f27d55dcf80723b5ba1cd8903bed1fd69f1b9e2e
license    : BSD-3-Clause
component  : programming
summary    : OpenCV is an open source computer vision and machine learning software library.
description: |
    OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(ice)
    - pkgconfig(jasper)
    - pkgconfig(libavcodec)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(OpenEXR)
    - pkgconfig(python3)
    - pkgconfig(sm)
    - pkgconfig(xmu)
    - intel-tbb-devel
    - numpy
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-18009.patch
    %patch -p1 < $pkgfiles/security/cve-2017-1000450.patch

    #Use ippicv from $sources
    IPPNAME=$(basename $sources/ippicv_*_lnx_*.tgz)
    MD5SUM=$(md5sum $sources/$IPPNAME | cut -d" " -f1)
    mkdir -p .cache/ippicv
    cp $sources/$IPPNAME .cache/ippicv/$MD5SUM-$IPPNAME

    mkdir build && cd build
    %cmake -DWITH_GPHOTO2=OFF \
        -DWITH_IPP=ON \
        -DWITH_OPENGL=ON \
        -DWITH_OPENCL=ON \
        -DWITH_TBB=ON \
        -DENABLE_CXX11=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_PERF_TESTS=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_DOCS=OFF \
        -DBUILD_WITH_DEBUG_INFO=OFF \
        -DENABLE_SOLUTION_FOLDERS=ON \
        -DOPENCV_ENABLE_NONFREE=ON \
        -DWITH_QT=OFF \
        -DOPENCV_FORCE_PYTHON_LIBS=ON \
        -DENABLE_PRECOMPILED_HEADERS=OFF \
           ..
build      : |
    %make -C build
install    : |
    %make_install -C build
