name       : opencv
version    : 3.1.0
release    : 7
source     :
    - https://github.com/opencv/opencv/archive/3.1.0.tar.gz : f00b3c4f42acda07d89031a2ebb5ebe390764a133502c03a511f67b78bbd4fbf
    - https://raw.githubusercontent.com/Itseez/opencv_3rdparty/81a676001ca8075ada498583e4166079e5744668/ippicv/ippicv_linux_20151201.tgz : 4333833e40afaa22c804169e44f9a63e357e21476b765a5683bcb3760107f0da
license    : BSD-3
component  : programming
summary    : OpenCV is an open source computer vision and machine learning software library.
description: |
    OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(ice)
    - pkgconfig(OpenEXR)
    - pkgconfig(python-2.7)
    - pkgconfig(sm)
    - pkgconfig(xmu)
    - intel-tbb-devel
    - jasper-devel
    - libjpeg-turbo-devel
    - numpy
setup      : |
    #Use ippicv from $sources
    MD5SUM=$(md5sum $sources/ippicv_linux*.tgz | cut -d" " -f1)
    mkdir -p 3rdparty/ippicv/downloads/linux-$MD5SUM
    cp $sources/ippicv_linux*.tgz 3rdparty/ippicv/downloads/linux-$MD5SUM

    %cmake -DWITH_GPHOTO2=OFF \
           -DWITH_IPP=ON \
           -DWITH_OPENGL=ON \
           -DWITH_TBB=ON \
           -DBUILD_SHARED_LIBS=ON \
           -DBUILD_PERF_TESTS=OFF \
           -DBUILD_TESTS=OFF \
           -DLIB_SUFFIX=64 .
build      : |
    %make
install    : |
    %make_install
    #Allow -lippicv to be found and get moved to -devel
    mv $installdir/usr/share/OpenCV/3rdparty/lib64/libippicv.a $installdir/usr/lib64
    rm -rf $installdir/usr/share/OpenCV/3rdparty
