name       : opencv
version    : 4.5.3
release    : 30
source     :
    - https://github.com/opencv/opencv/archive/refs/tags/4.5.3.tar.gz : 77f616ae4bea416674d8c373984b20c8bd55e7db887fd38c6df73463a0647bab
    - https://github.com/opencv/opencv_contrib/archive/4.5.3/opencv_contrib-4.5.3.tar.gz : 73da052fd10e73aaba2560eaff10cc5177e2dcc58b27f8aedf7c649e24c233bc
    - https://raw.githubusercontent.com/opencv/opencv_3rdparty/ippicv/master_20191018/ippicv/ippicv_2020_lnx_intel64_20191018_general.tgz : 08627fa5660d52d59309a572dd7db5b9c8aea234cfa5aee0942a1dd903554246
    - https://github.com/opencv/ade/archive/v0.1.1f.zip : 956e2e51da455ebb3d3ed1269dda44d233a2de620e5bdbdb32e0c0bb84b2c912
    - https://github.com/opencv/opencv_3rdparty/archive/34e4206aef44d50e6bbcd0ab06354b52e7466d26/opencv_3rdparty-34e4206aef44d50e6bbcd0ab06354b52e7466d26.tar.gz : d93c783cdf799da7e4a9209d169390424c4c198c1c9b5eeb78ffc890afe5f332
    - https://github.com/opencv/opencv_3rdparty/archive/fccf7cd6a4b12079f73bbfb21745f9babcd4eb1d/opencv_3rdparty-fccf7cd6a4b12079f73bbfb21745f9babcd4eb1d.tar.gz : e9abccbabcace092e5424073168cc86d422585d15d25569f01fb6503b109e0e1
license    :
    - BSD-3-Clause
    - EULA # ippicv
component  : programming.library
summary    : OpenCV is an open source computer vision and machine learning software library
description: |
    OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(hdf5)
    - pkgconfig(ice)
    - pkgconfig(libavcodec)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libgphoto2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(sm)
    - pkgconfig(xmu)
    - ceres-solver-devel
    - intel-tbb-devel
    - numpy
    - unzip
    - vulkan-headers
rundeps    :
    - numpy
    - devel :
        - qt5-base-devel
setup      : |
    # Use ippicv from $sources
    IPPNAME=$(basename $sources/ippicv_*_lnx_*.tgz)
    IPPMD5SUM=$(md5sum $sources/$IPPNAME | cut -d " " -f1)
    mkdir -p .cache/ippicv
    cp $sources/$IPPNAME .cache/ippicv/$IPPMD5SUM-$IPPNAME

    ADENAME=$(basename $sources/v0.1.1f.zip)
    ADEMD5SUM=$(md5sum $sources/$ADENAME | cut -d " " -f1)
    mkdir -p .cache/ade
    cp $sources/$ADENAME .cache/ade/$ADEMD5SUM-$ADENAME

    mkdir boostdesc
    mkdir -p .cache/xfeatures2d/boostdesc
    tar xf $sources/opencv_3rdparty-34e4206*.tar.gz --strip-components=1 -C boostdesc
    for int in boostdesc/boostdesc_*.i; do
        BOOSTDESCNAME=$(basename $int)
        BOOSTDESCMD5SUM=$(md5sum $int | cut -d " " -f1)
        cp $int .cache/xfeatures2d/boostdesc/$BOOSTDESCMD5SUM-$BOOSTDESCNAME
    done

    mkdir vgg
    mkdir -p .cache/xfeatures2d/vgg
    tar xf $sources/opencv_3rdparty-fccf7cd*.tar.gz --strip-components=1 -C vgg
    for int in vgg/vgg_*.i; do
        VGGNAME=$(basename $int)
        VGGMD5SUM=$(md5sum $int | cut -d " " -f1)
        cp $int .cache/xfeatures2d/vgg/$VGGMD5SUM-$VGGNAME
    done

    tar xf $sources/opencv_contrib-*.tar.gz
    mv opencv_contrib* contrib

    #patch -p1 < $pkgfiles/Support-building-with-OpenEXR-3.patch

    %cmake_ninja \
        -DOPENCV_GENERATE_PKGCONFIG=ON \
        -DOPENCV_EXTRA_MODULES_PATH=$workdir/contrib/modules \
        -DWITH_GPHOTO2=ON \
        -DWITH_IPP=ON \
        -DWITH_OPENGL=ON \
        -DOpenGL_GL_PREFERENCE="GLVND" \
        -DWITH_VULKAN=ON \
        -DWITH_OPENCL=ON \
        -DWITH_TBB=ON \
        -DENABLE_CXX11=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_PERF_TESTS=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_DOCS=OFF \
        -DBUILD_WITH_DEBUG_INFO=OFF \
        -DBUILD_opencv_python2=OFF \
        -DENABLE_SOLUTION_FOLDERS=ON \
        -DOPENCV_ENABLE_NONFREE=ON \
        -DWITH_QT=ON \
        -DOPENCV_FORCE_PYTHON_LIBS=ON \
        -DENABLE_PRECOMPILED_HEADERS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
