name       : opencv
version    : 3.0.0
release    : 2
source     :
    - https://github.com/Itseez/opencv/archive/3.0.0.tar.gz : da51a4e459b0bcbe14fb847c4f168415f421765fb91996f42b9e1ce0575f05d5
license    : BSD-3
summary    : OpenCV is an open source computer vision and machine learning software library.
description: |
    OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library.
libsplit : no
builddeps  :
    - pkgconfig(eigen2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libdc1394-2)
    - pkgconfig(ice)
    - pkgconfig(OpenEXR)
    - pkgconfig(python-2.7)
    - pkgconfig(sm)
    - pkgconfig(xmu)
    - intel-tbb-devel
    - numpy
build      : |
    %patch -p1 < $pkgfiles/5041tbb.diff
    %cmake -D WITH_GPHOTO2=OFF -D WITH_OPENGL=ON -D WITH_TBB=ON \
        -D BUILD_opencv_features2d=OFF -D BUILD_opencv_calib3d=OFF -D BUILD_opencv_shape=OFF -D BUILD_opencv_ts=OFF \
        -D BUILD_opencv_photo=OFF -D BUILD_opencv_video=OFF -D BUILD_opencv_superres=OFF -D BUILD_opencv_objdetect=OFF \
        -D BUILD=SHARED=LIBS=ON -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -DLIB_SUFFIX=64 .
    %make
install   : |
    %make_install
